/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:f4ffcabf-c4a1-47d6-9116-fdad8551b344",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_8sFOU4kk2",
    "aws_user_pools_web_client_id": "2spsaoioplsm8af5a2prj4itd0",
    "oauth": {}
};


export default awsmobile;
